### ISSUE TITLE
Can't start >= 1.20.2

### ISSUE THREAD

**Issue by laenion** [alexivkin/minecraft-launcher#3]
Trying to start a Minecraft version >= 1.20.2 (including the current 1.20.4) fails with the following message:

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid UUID string: 0
	at java.base/java.util.UUID.fromString1(UUID.java:280)
	at java.base/java.util.UUID.fromString(UUID.java:258)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:151)
```

**Comment by alexivkin** [comment]
Thanks for reporting. Fixed.
